### ISSUE TITLE
/timetable returns an error

### ISSUE THREAD

**Issue by raikasdev** [qlma/app#4]
local variable 'group' referenced before assignment
/app/timetable/views.py, line 23, in timetable
![Django error](https://loota.raikas.xyz/Db7woTc.png)

**Comment by jounile** [comment]
This happened because the user was not assigned to a group. 
Now there is a check to prevent this from happening and certain features are disabled before admin adds the new user to a certain group. The idea is to prevent a self-registered user from seeing private content before being approved & assigned to a group by admin.
